# Generated by Django 3.1.7 on 2021-04-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1995-12-02'),
            preserve_default=False,
        ),
    ]
